name: Ci_Cd_Test1
env:
  EB_PACKAGE_S3_BUCKET_NAME : "cf-templates-p674dmzm3lbr-ap-northeast-1"
  EB_APPLICATION_NAME       : "AWS_S3"
  EB_ENVIRONMENT_NAME       : "Awss3-env"
  DEPLOY_PACKAGE_NAME       : "aws_deploy.zip"
  AWS_REGION_NAME           : "ap-northeast-1"


on:
  push: 
    branches:
      - main
      

jobs:
  cfn-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v1

      - name: Create zip deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.YOUR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.YOUR_SECRET_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}

      - name: Copy Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: Print Happy Massage for CI finish
        run : echo "CI Pipeline part finished successfully!"
        
      - name: Deploy to EB
        uses: Emir3339/beanstalk-deploy@v20
        with:
          aws_access_key    : ${{ secrets.YOUR_ACCESS_KEY }}
          aws_secret_key    : ${{ secrets.YOUR_SECRET_KEY }}
          application_name  : ${{ env.EB_APPLICATION_NAME }}
          environment_name  : ${{ env.EB_ENVIRONMENT_NAME }}
          aws-region        : ${{ env.AWS_REGION_NAME }}
          deployment_package: ${{ env.DEPLOY_PACKAGE_NAME }}
