name: Ci_Cd_Test1
env:
  EB_PACKAGE_S3_BUCKET_NAME : "cf-templates-p674dmzm3lbr-ap-northeast-1"
  EB_APPLICATION_NAME       : "AWS_S3"
  EB_ENVIRONMENT_NAME       : "Awss3-env"
  DEPLOY_PACKAGE_NAME       : "aws_deploy.zip"
  AWS_REGION_NAME           : "ap-northeast-1"

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  push: 
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cfn-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v1

      - name: Create zip deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.YOUR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.YOUR_SECRET_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}

      - name: Copy Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

      - name: Print Happy Massage for CI finish
        run : echo "CI Pipeline part finished successfully!"

  cd_part:
    runs-on: ubuntu-latest
    needs  : [cfn-deployment]
  
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
  
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.YOUR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.YOUR_SECRET_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}
  
      - name: Deploy to EB
        run : |
          aws cloudformation deploy \
          --stack-name cf-templates-p674dmzm3lbr-ap-northeast-1 \
          --template-file aws_deploy/awstest1.yaml \
  
      - name: Print Happy Message for CD finish
        run: echo "CD Pipeline part Finished successfully"
